/// ----------------------------------------------------------------------------
/// @function dialogue_load_localisation(parameters)
/// ----------------------------------------------------------------------------
/// @description
/// This function is used to load a CSV file generated by "dialogue_build_localisation"
///
/// NOTE: Only one localisation can be active at any time.
///
/// NOTE: The localisation is applied the next time a dialogue instance executes
/// a flow control function.
///
/// NOTE: Any lines and options that don't have a #line tag and a corresponding
/// value in the active localisation file will be displayed in their native language.
/// ----------------------------------------------------------------------------
/// @param {string} filepath
/// The filepath of the localisation file to load.
///
/// NOTE: The filepath is relative to CHATTERBOX_INCLUDED_FILES_SUBDIRECTORY.
/// ----------------------------------------------------------------------------
/// @returns {undefined}
/// ----------------------------------------------------------------------------
function dialogue_load_localisation(parameters) {
    if (!is_struct(parameters)) { parameters = {} }
    var _filepath = parameters[$ "filepath"]
    ChatterboxLocalizationLoad(_filepath)
    return undefined
}